---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    - name: post_id
      in: path
      type: string
      description: post_id
      required: true
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: comment
        in: body
        schema:
          type: object
          properties:
            text:
              type: string
            author_id:
              type: integer
            post_id:
              type: integer
          required:
          - text
          - author_id
          - post_id
      consumes:
      - application/json
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/posts":
    parameters:
    - in: header
      type: string
      name: Authorization
      required: true
      description: Client token
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    get:
      summary: list posts
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    post:
      summary: create post
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/posts/new":
    parameters:
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    get:
      summary: new post
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/posts/{id}/edit":
    parameters:
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: edit post
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/posts/{id}":
    parameters:
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show post
      responses:
        '200':
          description: successful
    patch:
      summary: update post
      responses:
        '200':
          description: successful
    put:
      summary: update post
      responses:
        '200':
          description: successful
    delete:
      summary: delete post
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    post:
      summary: create user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            bio:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - bio
          - password
          - password_confirmation
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - in: header
      type: string
      name: Authorization
      required: true
      description: Client token
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show user
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
